Tam.Ebilling.Web/Areas/Core/Controllers/CustomerController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tam.Ebilling.Domain;
using Tam.Ebilling.Infrastructure.Mvc;
using Tam.Ebilling.Service;

namespace Tam.Ebilling.Web.Areas.Core.Controllers
{
    public class CustomerController : WebControllerBase
    {
        // GET: Core/Log
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var result = Service<CustomerService>().GetDataSourceResult(request);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CustomerDetail([DataSourceRequest] DataSourceRequest request, string customer_code, int business_unit_id)
        {
            var cust = Service<CustomerService>().GetCustomer(customer_code, business_unit_id.ToString());

            Customer empObj = new Customer();
            empObj.customer_code = cust.customer_code;
            empObj.business_unit_id = cust.business_unit_id;
            empObj.customer_name = cust.customer_name;
            empObj.customer_group = cust.customer_group;

            return PartialView("~/Areas/Core/Views/Customer/Form/CustomerModal.cshtml", empObj);
        }

        public ActionResult Save(Customer customer)
        {
            var result = Service<CustomerService>().Save(customer);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

Tam.Ebilling.Web/Areas/Core/Views/Customer/Script/_Customer.cshtml
<script type="text/javascript">
    function CustomerManagement() {
        return {
            InitManagement: function () {
                this.InitControls();
                this.InitValidation();
                this.InitHandlers();
            },

            InitControls: function () {

            },

            InitValidation: function () {

            },

            InitHandlers: function () {
                $(".k-grid").on("click", ".k-grid-update", function () {
                    //alert('CEK');
                    var $el = $(this),
                        $grid = $el.closest(".k-grid").data("kendoGrid");

                    var customer_code = $el.data("customercode");
                    var business_unit_id = $el.data("businessunitid");

                    var urlstring = '@Url.Action("CustomerDetail", "Customer")?customer_code=' + customer_code + "&business_unit_id=" + business_unit_id;

                    $.ajax({
                        url: urlstring,
                        dataType: 'html',
                        success: function (data) {
                            $('#CustomerModal').find("div.modal-content").html(data);
                            $("#CustomerModal").modal("show");
                        },
                        error: function () {
                            $('#CustomerModal').modal('toggle');
                        }
                    });
                });
            }
        };
    }

    function save() {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Save", "Customer")',
            data: $.helper.form.serializeObject($('#formContainer')),
            success: function (e) {
                $("#CustomerModal").modal("hide");
                swal("Info", "Customer saved", "success", { timer: 2000 });
            },
            error: function (e) {
                swal("Error", "Customer not saved", "error", { timer: 2000 });
            }
        });
    }

    $(document).ready(function () {
        App.CustomerManagement = new CustomerManagement();
        App.CustomerManagement.InitManagement();
    });
</script>