Tam.Ebilling.Web/Areas/Core/Controllers/ConfigController.cs
using Kendo.Mvc.UI;
using System.Net;
using System.Web.Mvc;
using Tam.Ebilling.Domain;
using Tam.Ebilling.Service;
using Tam.Ebilling.Infrastructure.Mvc;

namespace Tam.Ebilling.Web.Areas.Core.Controllers
{
    public class ConfigController : WebControllerBase
    {

        [HttpPost]
        public ActionResult Read([DataSourceRequest] Kendo.Mvc.UI.DataSourceRequest request)
        {
            var result = Service<ConfigService>().GetDataSourceResult(request);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

Tam.Ebilling.Web/Areas/Core/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tam.Ebilling.Infrastructure.Mvc;
using Tam.Ebilling.Service;
using Agit.Common.Email;

namespace Tam.Ebilling.Web.Areas.Core.Controllers
{
    public class SettingController : WebControllerBase
    {
        // GET: Core/Setting
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendTestEmail(EmailSettingRequest emailSetting, string toEmail)
        {
            string emailContent = string.Format("Email testing");

            EmailMessage mail = new EmailMessage();
            mail.From = emailSetting.FromAddress;
            mail.DisplayName = emailSetting.FromDisplay;
            mail.Subject = "Email Tester";
            mail.Recipients.Add(toEmail);
            mail.Body = emailContent;

            EmailService mailService = new EmailService();

            mailService.Host = emailSetting.SmtpHost;
            mailService.Port = emailSetting.SmtpPort;
            mailService.UseDefaultCredentials = emailSetting.UseDefaultCredential;
            mailService.EnableSsl = emailSetting.EnableSSL;
            mailService.User = emailSetting.Username;
            mailService.Password = emailSetting.Password;

            mailService.Send(mail);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
    }
}

Tam.Ebilling.Web/Areas/Core/Views/Setting/Component/_ConfigGrid.cshtml
@(Html.Kendo().Grid<Tam.Ebilling.Domain.Config>()
    .Name("ConfigGrid")
    .Columns(columns =>
    {
        columns.Bound(o => o.ID).Sortable(false).HtmlAttributes(new { @class = "text-center" }).ClientTemplate(
            @"
            <div class=""btn-group"">
                <button class='btn btn-xs btn-default trigger-edit'>Edit</button>
                <!-- <a class='btn btn-xs btn-danger k-grid-delete'>Delete</a> -->
            </div>
            "
        ).Title("Action").Width(65).MinScreenWidth(800);
        columns.Bound(o => o.ConfigText).Title("Key");
        columns.Bound(o => o.ConfigValue).Title("Value").ClientTemplate(@"
            <div # if (ConfigDataType == 'select' || ConfigDataType == 'date' || ConfigDataType == 'bool') { # data-value='#:ConfigValue#' # } # data-name='#: ConfigKey #' data-mode='inline' # if (ConfigText != null || ConfigDataType == 'bool') { # data-source='#= ConfigDataType == 'bool' ? '[""True"", ""False""]' : ConfigText #' # } # class='editable' data-type='#: ConfigDataType == 'bool' ? 'select' : ConfigDataType #' data-pk='#:ID#'>#if (ConfigDataType == 'wysihtml5') { ##=ConfigValue## } else { ##:ConfigValue## } #</div>
        ");
        //columns.Bound(o => o.ConfigText).Title("Text");
    })
    .ToolBar(toolbar => toolbar.Custom().Text("Refresh Config").HtmlAttributes(new { id = "refreshConfigBtn" }))
    .NoRecords(conf => conf.Template("No General Setting to display"))
    .Pageable(pageable => pageable.PageSizes(new[] { 5, 10, 20, 100, 200 }).ButtonCount(5))
    .Sortable()
    .Resizable(o => o.Columns(true))
    .Reorderable(o => o.Columns(true))
    .DataSource(dataSource => dataSource
        .Ajax()
        .Read(read => read.Url(@Url.Action("Read", "Config", new { area = "Core" })))
        .Create(create => create.Url(@Url.Action("Create", "Config", new { area = "Core" })))
        .Update(update => update.Url(@Url.Action("Update", "Config", new { area = "Core" })))
        .Destroy(destroy => destroy.Url(@Url.Action("Delete", "Config", new { area = "Core" })))
        .PageSize(100)
        .Sort(sort => sort.Add(x => x.ConfigKey))
        .Model(model =>
        {
            model.Id(p => p.ID);
            model.Field(p => p.ID).Editable(false);
        })
    .Group(group =>
    {
        group.Add(x => x.Module);
    })
    )
)

Tam.Ebilling.Web/Areas/Core/Views/Setting/Component/_EmailSettingForm.cshtml
@model Tam.Ebilling.Service.EmailSettingRequest 
    
<form id = "EmailSmtpSettingsForm" >
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label>From Address</label>
                @Html.TextBoxFor(x => x.FromAddress, new { @class = "form-control" })
            </div>
        </div>
         <div class="col-md-6 col-sm-12">
             <div class="form-group">
                 <label>From Display</label>
                 @Html.TextBoxFor(x => x.FromDisplay, new { @class = "form-control", @maxlength="128" })
             </div>
         </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label>SMTP Host</label>
                @Html.TextBoxFor(x => x.SmtpHost, new { @class = "form-control", @maxlength = "64" })
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label>SMTP Port</label>
                @Html.TextBoxFor(x => x.SmtpPort, new { @class = "form-control", @maxlength = "5", @type = "number" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label>Username</label>
                @Html.TextBoxFor(x => x.Username, new { @class = "form-control", @maxlength = "128" })
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label>Password</label>
                @Html.PasswordFor(x => x.Password, new { @class = "form-control", @maxlength = "128", @autocomplete="off" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="mt-checkbox-list">
            <label class="mt-checkbox">
                Enable SSL
                @Html.CheckBoxFor(m => m.EnableSSL)
                <span></span>
            </label>
            <label class="mt-checkbox">
                Use Default Credential
                @Html.CheckBoxFor(m => m.UseDefaultCredential)
                <span></span>
            </label>
        </div>
    </div>

        
    <h5>Test Email Setting</h5>
    <div class="row">
        <div class="form-group col-md-4">
            <input id="TestEmailAddressInput" type="text" class="form-control" value="">
        </div>
        <div class="form-group col-md-2">
            <button id="SendTestEmailButton" class="btn green-haze" type="button">Send Email Test</button>
        </div>
    </div>

    <div>
        <button type="button" class="btn green" id="btnSaveEmailSetting">Save</button>
    </div>
</form>

Tam.Ebilling.Web/Areas/Core/Views/Setting/Component/_EmailTemplateGrid.cshtml
@(Html.Kendo().Grid<Tam.Ebilling.Domain.EmailTemplate>()
    .Name("EmailTemplateGrid")
    .Columns(columns =>
    {
        columns.Bound(o => o.ID).Sortable(false).HtmlAttributes(new { @class = "text-center" }).ClientTemplate(
            @"
            <div class=""btn-group"">
                <a class='btn btn-xs btn-default k-grid-edit' data-modal='EmailTemplateModal'>Edit</a>
                <!-- <a class='btn btn-xs btn-danger k-grid-delete'>Delete</a> -->
            </div>
            "
        ).Title("Action").Width(65).MinScreenWidth(800);
        columns.Bound(o => o.MailKey).Title("Key");
        columns.Bound(o => o.Title).Title("Title");
        columns.Bound(o => o.MailFrom).Title("Mail From");
        columns.Bound(o => o.DisplayName).Title("Display Name");
        columns.Bound(o => o.Subject).Title("Subject");
    })
    .NoRecords(conf => conf.Template("No Email Template to display"))
    .Pageable(pageable => pageable.PageSizes(new[] { 5, 10, 20, 100, 200 }).ButtonCount(5))
    .Sortable()
    .Resizable(o => o.Columns(true))
    .Reorderable(o => o.Columns(true))
    //.Editable(editable => editable.Mode(GridEditMode.PopUp))
    .DataSource(dataSource => dataSource
        .Ajax()
        .Read(read => read.Url(@Url.Action("Read", "EmailTemplate", new { area = "Core" })))
        .Create(create => create.Url(@Url.Action("Create", "EmailTemplate", new { area = "Core" })))
        .Update(update => update.Url(@Url.Action("Update", "EmailTemplate", new { area = "Core" })))
        .Destroy(destroy => destroy.Url(@Url.Action("Delete", "EmailTemplate", new { area = "Core" })))
        .PageSize(20)
        .Sort(sort => sort.Add(x => x.MailKey))
        .Model(model =>
        {
            model.Id(p => p.ID);
            model.Field(p => p.ID).Editable(false);
        })
    //.Group(group =>
    //{
    //    group.Add(x => x.Module);
    //})
    )
)

Tam.Ebilling.Web/Areas/Core/Views/Setting/Component/_SecurityForm.cshtml
<div>
    <form id="PasswordComplexitySettingsForm">
        <div class="form-group">
            <label style="font-weight:bold; font-size:16px;">Password Complexity</label>
            <div class="mt-checkbox-list">
                <label class="mt-checkbox">
                    Use Default Settings
                    <input type="checkbox" value="1" name="test">
                    <span></span>
                </label>
                <label class="mt-checkbox">
                    Require Digit
                    <input type="checkbox" value="1" name="test">
                    <span></span>
                </label>
                <label class="mt-checkbox">
                    Require Uppercase
                    <input type="checkbox" value="1" name="test">
                    <span></span>
                </label>
                <label class="mt-checkbox">
                    Require Lowercase
                    <input type="checkbox" value="1" name="test">
                    <span></span>
                </label>
                <label class="mt-checkbox">
                    Require Non Alphanumeric
                    <input type="checkbox" value="1" name="test">
                    <span></span>
                </label>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Password Length</label>
                        <input type="number" name="RequiredLength" class="form-control">
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label style="font-weight:bold; font-size:16px;">User Lockout</label>
            <div class="mt-checkbox-list">
                <label class="mt-checkbox">
                    Enable user account locking on failed login attempts
                    <input type="checkbox" value="1" name="test">
                    <span></span>
                </label>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Maximum attempt on failed login</label>
                        <input type="number" name="FailedLogin" class="form-control">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Account locking duration</label>
                        <input type="number" name="LockingDuration" class="form-control">
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label style="font-weight:bold; font-size:16px;">Two Factor Login</label>
            <div class="mt-checkbox-list">
                <label class="mt-checkbox">
                    Enable two factor login
                    <input type="checkbox" value="1" name="test">
                    <span></span>
                </label>
                <label class="mt-checkbox">
                    Enable email verification (OTP)
                    <input type="checkbox" value="1" name="test">
                    <span></span>
                </label>
            </div>
        </div>

        <div>
            <button type="button" class="btn green" id="btnSaveSecurity">Save</button>
        </div>
    </form>
</div>