Tam.Ebilling.Web/Areas/Core/Controllers/InvoiceController.cs
using Kendo.Mvc.UI;
using Microsoft.Reporting.WebForms;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tam.Ebilling.Domain;
using Tam.Ebilling.Infrastructure.Mvc;
using Tam.Ebilling.Infrastructure.Session;
using Tam.Ebilling.Infrastructure.Enum;
using Tam.Ebilling.Service;
using Agit.Helper.Helper;
using Tam.Ebilling.Infrastructure.Helper;
using System.Net;
using Tam.Ebilling.Infrastructure.Cache;
using Tam.Ebilling.Reporting;
using NPOI.HSSF.UserModel;
using NPOI.HSSF.Util;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System.Text;
using System.Globalization;
using System.Data;
using Tam.Ebilling.Web.Areas.Core.Models;
using System.Text.RegularExpressions;
using NPOI.SS.Formula.Functions;
using Agit.Helper.Extension;

namespace Tam.Ebilling.Web.Areas.Core.Controllers
{
    public class InvoiceController : CommonFeatureController
    {
        // GET: Core/Log
        public ActionResult Index()
        {
            var transactiontype = Service<TransactionTypeService>().GetTransactionType();
            ViewBag.TransactionType = transactiontype;

            var arstatus = Service<ARStatusService>().GetARStatus();
            ViewBag.ARStatus = arstatus;

            var customer = Service<CustomerService>().GetCustomer();
            ViewBag.CustomerName = customer;

            var cust = SessionManager.RoleStr;
            ViewBag.Customer = cust;

            ViewBag.UserType = SessionManager.UserType;
            ViewBag.IsAllowedExportToExcel = IsAllowed("export_to_excel") || ViewBag.UserType == "Customer";
            ViewBag.IsAllowedDownloadAll = IsAllowed("download_all") || ViewBag.UserType == "Customer";
            ViewBag.IsAllowedDownloadInvoice = IsAllowed("download_invoice") || ViewBag.UserType == "Customer";
            ViewBag.IsAllowedDownloadInvoiceQR = IsAllowed("download_invoice_qr") || ViewBag.UserType == "Customer";
            ViewBag.IsAllowedDownloadAttachment = IsAllowed("download_attachment") || ViewBag.UserType == "Customer";
            ViewBag.IsAllowedDownloadPI = IsAllowed("download_pi") || ViewBag.UserType == "Customer";
            ViewBag.IsAllowedUploadInvoice = IsAllowed("upload_invoice") || ViewBag.UserType == "Customer";
            ViewBag.IsAllowedDownloadPPH2 = true; //IsAllowed("download_pph22") || ViewBag.UserType == "Customer";
            ViewBag.IsAllowedDownloadWhtPDF = true;
            ViewBag.IsAllowedDownloadTaxInvoice = true;
            return View();
        }
        
        [HttpPost]
        public ActionResult Read([DataSourceRequest] Kendo.Mvc.UI.DataSourceRequest request)
        {
            
            var result = Service<InvoiceService>().GetGridInitDataSourceResult(request, Convert.ToInt16(EnumHelper.GetDescription(InvoiceType.Invoice)), SessionManager.RoleStr);

            return Json(result, JsonRequestBehavior.AllowGet);
 
        }

        public void ExportZip([DataSourceRequest] DataSourceRequest request)
        {
            request.Page = 0;
            request.PageSize = 0;

            string linkdata = string.Empty;
            string namapath = string.Empty;
            string filenamepdf = string.Empty;
            var username = Service<ParameterService>().GetParameter("file_impersonate_user").value1;
            var domain = Service<ParameterService>().GetParameter("file_impersonate_domain").value1;
            var userdomain = domain + "\\" + username;
            var password = Service<ParameterService>().GetParameter("file_impersonate_password").value1;

            var credential = new NetworkCredential(userdomain, password);
            string fileserver = Service<ParameterService>().GetParameter("file_server").value1;
            string filepath = Service<ParameterService>().GetParameter("file_repo_path_tax").value1;
            string file = "\\\\" + fileserver + "\\" + filepath;

            try
            {
                using (new NetworkConnection(file, credential))
                {
                    var result = Service<InvoiceService>().GetViewDataSourceResult(request, Convert.ToInt16(EnumHelper.GetDescription(InvoiceType.Invoice)), SessionManager.RoleStr);
                    //var result = Service<InvoiceService>().GetGridInitDataSourceResult(request, Convert.ToInt16(EnumHelper.GetDescription(InvoiceType.Invoice)), SessionManager.RoleStr);
                    var outputfile = "TAXINVOICE - " + DateTime.Now.ToString("yyyyMMdd") + ".zip";

                    using (var memoryStream = new MemoryStream())
                    {
                        using (var ziparchive = new ZipArchive(memoryStream, ZipArchiveMode.Create, true))
                        {
                            foreach (Invoice inv in result.Data)
                            {       
                                if (inv.tax_attc_url != null)
                                {
                                    var value = inv.tax_attc_url;
                                    string Result = Path.GetFileNameWithoutExtension(value) + ".pdf";
                                    var url = Path.Combine(file, Result);
                                    if (System.IO.File.Exists(url) == true)
                                    {
                                        namapath = Path.GetFileNameWithoutExtension(outputfile) + "\\" + Path.GetFileNameWithoutExtension(inv.tax_attc_url) + "\\" + Path.GetFileNameWithoutExtension(inv.tax_attc_url) + ".pdf";
                                        var fileInArchive = ziparchive.CreateEntry(namapath);

                                        using (FileStream _file = new FileStream(url, FileMode.Open, FileAccess.Read))
                                        {
                                            byte[] bytes = new byte[_file.Length];

                                            _file.Read(bytes, 0, (int)_file.Length);

                                            using (var zipStream = fileInArchive.Open())
                                            using (var fileToCompressStream = new MemoryStream(bytes))
                                            {
                                                fileToCompressStream.CopyTo(zipStream);
                                            }
                                        }
                                    }
                                    else if (System.IO.File.Exists(url) == false)
                                    {
                                        ziparchive.CreateEntry(Path.GetFileNameWithoutExtension(outputfile) + "\\" + Path.GetFileNameWithoutExtension(inv.tax_attc_url) + "\\" + Path.GetFileNameWithoutExtension(inv.tax_attc_url) + ".NOTFOUND");
                                    }
                                }
                                else
                                {
                                    //ziparchive.CreateEntry(Path.GetFileNameWithoutExtension(outputfile) + "\\" + Path.GetFileNameWithoutExtension(inv.tax_attc_url) + "\\" + Path.GetFileNameWithoutExtension(inv.tax_attc_url) + ".NOTFOUND");
                                    //throw new Exception("File Not Found !");
                                }
                            }
                            ziparchive.Dispose();

                        }
                        DownloadFinish();
                        Response.Clear();
                        Response.AddHeader("Access-Control-Allow-Origin", "*");
                        Response.ContentType = "application/octet-stream";
                        Response.AddHeader("content-disposition", "attachment;filename=" + outputfile);
                        Response.BinaryWrite(memoryStream.ToArray());
                        Response.Flush();
                        Response.End();
                    }
                }
            }
            //catch (FileNotFoundException e)
            //{
            //    throw new Exception(e.Message);
            //}
            catch (Exception e)
            {
                DownloadFinish();
                throw new Exception(e.Message);
            }
        }

        public void ExportZipInvoice([DataSourceRequest] DataSourceRequest request) 
        {
            byte[] fileBytes, zipBytes;
            string mimeType, extension;

            request.Page = 0;
            request.PageSize = 0;
            string filename = string.Empty;
            
            //var result = Service<InvoiceService>().GetViewDataSourceResult(request, Convert.ToInt16(EnumHelper.GetDescription(InvoiceType.Invoice)), SessionManager.RoleStr);
            var result = Service<InvoiceService>().GetGridInitDataSourceResult(request, Convert.ToInt16(EnumHelper.GetDescription(InvoiceType.Invoice)), SessionManager.RoleStr);
            var outputfile = "INVOICE - " + DateTime.Now.ToString("yyyyMMdd") + ".zip";
            string user = SessionManager.Current;
            string userid = "";
            if (user != "TAM\\Mayumi" || user != "TAM\\frans" || user != "TAM\\ronnyk102181" || user != "TAM\\indah.gustiana" || user != "TAM\\aliandy.syahriel")
            {
                user = userid;
            }
            else
            {
                user = SessionManager.Current;
            }
            string name = SessionManager.Name;
            string nameid = "";
            if (name != "Mayumi Eguchi" || name != "Frans lhutan B" || name != "Ronny Kusgianto" || name != "Indah Sari Gustiana" || name != "Aliandy Syahriel")
            {
                name = nameid;
            }
            else
            {
                name = SessionManager.Name;
            }
            using (var memoryStream = new MemoryStream())
            {
                using (var ziparchive = new ZipArchive(memoryStream, ZipArchiveMode.Create, true))
                {

Tam.Ebilling.Web/Areas/Core/Views/SummaryInvoice/Form/BuktiTransferUpload.cshtml
@using Tam.Ebilling.Domain
@using Tam.Ebilling.Service
@model Tam.Ebilling.Domain.Invoice
<style>
    .k-upload, .k-dropzone {
        background-color: #fff;
    }
</style>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title-attachment">Payment Confirmation</h4>
</div>
<div class="modal-body" style="min-height:300px">
    <div class="col-md-12">
        <div class="coll-md-12">
            @(Html.Kendo().Upload()
            .Name("files")
            .HtmlAttributes(new { aria_label = "files" })
            .Async(a => a
                .SaveUrl(@Url.Action("Upload", "AttachmentTransfer", new { Area = "Core" }))
                .AutoUpload(true)
            )
            .Events(evt =>
            {
                evt.Select("onSelectUpload");
                evt.Success("onSuccessUploadInitial");
                evt.Progress("onProgressUpload");
                evt.Complete("onCompleteUpload");
            })
            .ShowFileList(false)
            .Validation(v => v.AllowedExtensions(new string[] { ".pdf" }))
            )
        </div>
        <div class="col-md-6" style="margin-left:-10px">
            <form id="formInvoiceUpload">
                @(Html.Kendo().Grid<Invoice>()
            .Name("DocumentFileTransferInitial")
            .Columns(columns =>
            {
                columns.Bound(f => f.invoice_number).Title("Invoice Number").Width(150);
                columns.Bound(f => f.currency).Title("Curr").Width(80);
                columns.Bound(f => f.total_amount).Title("Amount").Width(150).ClientFooterTemplate("Summary: #=summary#");
            })
            .NoRecords(x => x.Template("No Documents"))
            .DataSource(dataSource => dataSource
            .Ajax()
            .PageSize(10)
            .Model(m => m.Id(f => f.amount_pph))
            .Read(read => read.Url(@Url.Action("GetListDocuments", "AttachmentNotaRetur", new { area = "Core" })).Data("getDocumentParameter"))
            )

                )
            </form>
        </div>
        <div class="col-md-6">
            <div class="form-body">
                <div class="form-group col-md-12" style="padding:0">
                    <label class="col-md-3 control-label" style="margin-top:5px">Payment Date</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control">
                    </div>
                </div>
                
                <div class="form-group col-md-12" style="padding:0">
                    <label class="col-md-3 control-label" style="margin-top:5px">Total Payment</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer" style="border-top: 1px solid #e5e5e5 !important">
    
        <button type="button" class="btn green" id="btnSave">Save</button>
        <button type="button" class="btn green" id="btnApprove">Approve</button>
        <button type="button" class="btn red" id="btnReject">Reject</button>
    
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#DocumentFileTransferInitial').contents().wrap('<div class="grid-scroll-container"></div>');
    });
</script>

Tam.Ebilling.Web/Areas/Core/Views/SummaryInvoice/Form/ScanInvoiceDocumentGrid.cshtml
@using Tam.Ebilling.Domain
@using Tam.Ebilling.Service
@model Tam.Ebilling.Domain.Invoice
@{
    List<udf_GetInvoiceNumber> listDoc = ViewBag.listDocument;
    string invoice = ViewBag.InvoiceNo;
    <input type="hidden" id="invoice" data-role="tagsinput" class="form-control" value="@ViewBag.InvoiceNo" />
    @(Html.Kendo().Grid<Tam.Ebilling.Domain.ScanInvoice>()
                                .Name("DocumentFileGrid")
                                .ToolBar(t => t.Template(
                                    @<text>
                                        <div class="row" style="margin-right:0">
                                            <div id="div-ddlupload" class="col-md-4">
                                                <select id="DocumentTypeUpload" class="form-control">
                                                    <option value="Pdf">Pdf</option>
                                                </select>
                                            </div>
                                            <div class="col-md-8">
                                                @(Html.Kendo().Upload()
                                                                                    .Name("files")
                                                                                    .HtmlAttributes(new { aria_label = "files" })
                                                                                    .Async(a => a
                                                                                        .SaveUrl(@Url.Action("Upload", "ScanInvoice", new { Area = "Core" }) + @"?invoice=" + @invoice)
                                                                                        .AutoUpload(true)
                                                                                    )
                                                                                    .Events(evt =>
                                                                                    {
                                                                                                        evt.Success("onSuccessUpload");
                                                                                                        evt.Progress("onProgressUpload");
                                                                                                        evt.Complete("onCompleteUpload");
                                                                                                    })
                                                                                    .ShowFileList(false)
                                                )
                                            </div>
                                        </div>
                                        <div class="row"> <div class="col-md-12">Maximum allowed file size is <strong>10MB</strong>.</div></div>
                                    </text>
                                                                ))
                                                                .Columns(columns =>
                                                                {
                                                                    columns.Bound(f => f.filename).HtmlAttributes(new { @class = "k-nowrwaptext" }).ClientTemplate(
                                                                    @"#if(invoice_number){#
                        <a href='" + Url.Action("Document", "ScanInvoice", new { Area = "Core" }) + @"?id=#:invoice_number#'>
                        <span #if(Status == ""Delete""){# style=""text-decoration: line-through;"" #}#>
                        #:filename#</span>
                        </a>
                        #}else{#
                        <a href='" + Url.Action("Temp", "Download", new { Area = "Core" }) + @"?filepath=#:filepath#&filename=#:filename#'>
                        <span #if(Status == ""Delete""){# style=""text-decoration: line-through;"" #}#>
                        #:filename#</span>
                        </a>
                    #}#"
                                                                    );
                                                        // columns.Bound(f => ).Title("Doc Type").Width(100);
                                                        columns.Bound(c => c.attachment_invoice_id).Title("Action").Width(75).HtmlAttributes(new { @class = "text-center", style = "overflow: visible;" }).Sortable(false).Filterable(false).ClientTemplate(
                                                                    @"#if(Status != ""Delete""){#
                        <a class=""btn btn-xs btn-danger k-grid-delete-doc"">Delete</a>
                        #}else{#
                        <a class=""btn btn-xs btn-success k-grid-undo-doc"">Undo</a>
                    #}#"
                                                                );
                                                                })
                                                            .NoRecords(x => x.Template("No Documents"))
                                                            .DataSource(dataSource => dataSource
                                                                .Ajax()
                                                                .PageSize(10)
                                                                .Model(m => m.Id(f => f.attachment_invoice_id))
                                                                .Read(read => read.Url(@Url.Action("GetListDocuments", "ScanInvoice", new { area = "Core" })).Data("getDocumentParameter"))
                                                            )
    )

Tam.Ebilling.Web/Areas/Core/Views/SummaryInvoice/Form/ScanInvoiceUpload.cshtml
@using Tam.Ebilling.Domain
@using Tam.Ebilling.Service
@model Tam.Ebilling.Domain.Invoice
@{
    List<udf_GetInvoiceNumber> listDoc = ViewBag.listDocument;
    string invoice = ViewBag.InvoiceNo;
    <input type="hidden" id="invoice" data-role="tagsinput" class="form-control" value="@ViewBag.InvoiceNo" />
    <input type="hidden" id="file" data-role="tagsinput" class="form-control" value="filename" runat="server" />
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title-attachment">Invoice</h4>
</div>

<div class="modal-body">
    <form id="formInvoiceUpload">
        @*@Html.HiddenFor(x => x.da_code)*@
        @(Html.Kendo().Grid(listDoc)
                    .Name("DocumentFileGridInitial")
                    .ToolBar(t => t.Template(
                                        @<text>
                                            <div class="row" style="margin-right:0">
                                                <div id="div-ddlupload" class="col-md-4">
                                                    <select id="DocumentTypeUploadInitial" class="form-control">
                                                        <option value="Dokumen">Invoice</option>
                                                    </select>
                                                </div>
                                                <div class="col-md-8">
                                                    @(Html.Kendo().Upload()
                                                                .Name("files")
                                                                .HtmlAttributes(new { aria_label = "files" })
                                                                .Async(a => a
                                                                    .SaveUrl(@Url.Action("Upload", "ScanInvoice", new { Area = "Core" }) + @"?invoice=" + @invoice)
                                                                    .AutoUpload(true)
                                                                )
                                                                .Events(evt =>
                                                                {
                                                                                evt.Select("onSelectUpload");
                                                                                evt.Success("onSuccessUploadInitial");
                                                                                evt.Progress("onProgressUpload");
                                                                                evt.Complete("onCompleteUpload");
                                                                            })
                                                                .ShowFileList(false)
                                                                .Validation(v => v.AllowedExtensions(new string[] { ".pdf" }))
                                                    )
                                                </div>
                                            </div>
                                        </text>
                                                              ))
                                                             .Columns(columns =>
                                                             {
                                                                 columns.Bound(f => f.filename).Title("File Name").HtmlAttributes(new { @class = "k-nowrwaptext" }).ClientTemplate(
                                                                 @"#if(invoice_number){#
                                     <a href='" + Url.Action("Document", "ScanInvoice", new { Area = "Core" }) + @"?id=#:attachment_invoice_id#'>
                                        <span #if(Status=='Delete'){# style='text-decoration: line-through;'#}#>
                                          #:filename#
                                        </span>
                                     </a>
                                             #}else{#
                                               <a href='" + Url.Action("Temp", "ScanInvoice", new { Area = "Core" }) + @"?filepath=#:filepath#&filename=#:filename#'>
                                                  <span #if(Status=='Delete'){# style='text-decoration: line-through;'#}#>
                                                     #:filename#
                                                  </span>
                                               </a>
                                                   #}#"
                                                                       ).Width(400);
                                                                 columns.Bound(f => f.attachment_invoice_id).Hidden(true);
                                                                 columns.Bound(c => c.invoice_number).Title("Action").Width(75).HtmlAttributes(new { @class = "text-center", style = "overflow: visible;" }).Sortable(false).Filterable(false).ClientTemplate(
                                                                   @"#if(DocumentType!='Pdf'){#
                                                   #if(Status != 'Delete'){#
                                                     <a class='btn btn-xs btn-danger k-grid-delete-doc' onclick='App.InvoiceManagement.DeleteDocumentInitial(this)'>Delete</a>
                                                       #}else{#
                                                       <a class='btn btn-xs btn-success k-grid-undo-doc' onclick='App.InvoiceManagement.UndoDocumentInitial(this)'>Undo</a>
                                                    #}}#"
                                                                );
                                                             })
                                                                       .NoRecords(x => x.Template("No Documents"))
                                                                        .DataSource(dataSource => dataSource
                                                                        .Ajax()
                                                                        .PageSize(10)
                                                                        .Model(m => m.Id(f => f.invoice_number))
                                                                        .Read(read => read.Url(@Url.Action("GetListDocuments", "ScanInvoice", new { area = "Core" })).Data("getDocumentParameter"))
                                                                    )

        )
    </form>
</div>
<div class="modal-footer" id="buttons">
    <div class="btn-group btn-group-m" id="actionbuttons">
        @if (AclHelper.HasPermission("App.InvoiceManagement.ScanInvoice.Save") == true)
        {
            <button type="button" class="btn green" id="btnSaveUploadScan" onclick="App.InvoiceManagement.SaveUploadDocumentInitial(this)">Save</button>
        }
    </div>
    <button type="button" class="btn dark btn-outline" data-dismiss="modal">Cancel</button>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#DocumentFileGridInitial').contents().wrap('<div class="grid-scroll-container"></div>');
    });
</script>

Tam.Ebilling.Web/Areas/Core/Views/SummaryInvoice/Form/TaxInvoice.cshtml
@model Tam.Ebilling.Domain.Invoice
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">Tax Invoice</h4>
</div>
<div class="row" style="margin-left:0px; margin-right: 0px">
    <div class="col-md-4 ">
        <div class="portlet light bordered" style="margin-top: 10px">
            <div class="portlet-body form">
                <form role="form">
                    <div class="form-body">
                        <div class="form-group">
                            <label>Tax</label>
                            <input type="text" id="tax" class="form-control" style="text-align: right" readonly value="@string.Format(" {0:#,0.00}",@Model.tax_invoice)" />

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="portlet light bordered" style="margin-top: 10px">
            <input type="hidden" id="invoiceNo" class="form-control" style="text-align: right" readonly value="@Model.invoice_number" />
            <input type="button" id="buttonId" class="k-button k-primary downloadBtn" value="Download PDF" />
            <!--  <a href="C://Users/solution/Source/Workspaces/TAM - eBilling/Tam.Ebilling.Master/Tam.Ebilling/Tam.Ebilling.Web/Areas/Core/Views/Invoice/contoh.pdf" target="_blank">Download PDF </a>
           -->
            <!--<a href="@Url.Action("DownloadPDF", "Invoice", new { Area = "Core" } )?Id='+@Model.invoice_number+' " class="k-button k-primary downloadBtn">

             Download PDF

         </a>-->
        </div>
        <div class="demo-section k-content" style="margin-top: 10px">
            @*<iframe src="@Url.Action("GetPDF", "Invoice", new { Area = "Core" })?Id='+@Model.invoice_number+' " height="500" width="500" onload="iframe_load()"></iframe>*@
            <!--<iframe src="D:\SHAREFOLDER\TaxInvoive.pdf" height="500" width="500"></iframe>-->
            <iframe id="taxInv" height="500" width="500"></iframe>

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        console.log("test");
        var invoice_number = '@Model.invoice_number';
        var invnumb = "'" + invoice_number + "'";

        $.ajax({
            url: '@Url.Action("ExportPDF", "Invoice", new { Area = "Core" })',
            //url: '/Core/Invoice/ExportPDF',
            type: 'POST',
            dataType: 'json',
            data: {
                id: invnumb
            },
            success: function (r) {
                console.log(r);
                if (r.result.Result == false) {
                    document.getElementById('buttonId').disabled = true;
                    swal("Warning", r.result.Message, "warning");
                } else {
                    document.getElementById('buttonId').disabled = false;
                    $("#taxInv").attr("src", "data:application/pdf;base64," + r.result.Url);
                }

            },
            error: function () {
                swal("Warning", "Failed to retrieve Tax Invoice", "warning");
            }
        });
    });
</script>

<script type="text/javascript">
    $('#buttonId').click(function () {
         var invoice_number = '@Model.invoice_number'
        var invnumb = "'" + invoice_number + "'";
        $.ajax({
            //url: '/Core/Invoice/ExportPDF',
            url: '@Url.Action("ExportPDF", "Invoice", new { Area = "Core" })',
            type: 'POST',
            dataType:'json',
            data: {
                id: invnumb
            },
            success: function (data) {
                var urldata = data.linkdata;
                if (urldata == "")
                {
                    //alert("File PDF Is Not Avalaible");
                }
                else
                {
                    var url = "@Url.Action("DownloadPDF", "Invoice", new { Area = "Core" })?id=" + invnumb;
                                window.location.href = url;
                            }
                        },
            error: function () {
                        }
                    });
    });

    function iframe_load()
    {

    }
</script>